 controller_list:
  - name: moveit/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - virtual_theta
      - virtual_x
      - virtual_y
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: arm_1/gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - gripper_finger_joint_r
      - gripper_finger_joint_l
