controller_list:
  - name: moveit/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - virtual_theta
      - virtual_x
      - virtual_y
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
    constraints:
      goal_tolerance: 0
      virtual_theta: {trajectory: 0.01, goal: 0.01}
      virtual_x: {trajectory: 0.01, goal: 0.01}
      virtual_y: {trajectory: 0.01, goal: 0.01}
      arm_joint_1: {trajectory: 0.01, goal: 0.01}
      arm_joint_2: {trajectory: 0.01, goal: 0.01}
      arm_joint_3: {trajectory: 0.01, goal: 0.01}
      arm_joint_4: {trajectory: 0.01, goal: 0.01}
      arm_joint_5: {trajectory: 0.01, goal: 0.01}

  - name: arm_1/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger_joint_r
      - gripper_finger_joint_l
    constraints:
      goal_tolerance: 0
      gripper_finger_joint_r: {trajectory: 0.01, goal: 0.01}
      gripper_finger_joint_l: {trajectory: 0.01, goal: 0.01}
